### ISSUE TITLE
Where does this paper published on?

### ISSUE THREAD

**Issue by machanic** [max-andr/square-attack#1]
I cannot find the place of the official journal or conference that the square attack published on? Does this paper only published on ArXiv website?

**Comment by max-andr** [comment]
The paper is under review currently :)

In case you want to cite it, feel free to cite the arXiv version, the bibtex is provided in the README.

**Comment by max-andr** [comment]
Update: the paper has been accepted at ECCV'20. 

In case you want to cite it, please cite it as:
```
@article{ACFH2020square,
  title={Square Attack: a query-efficient black-box adversarial attack via random search},
  author={Andriushchenko, Maksym and Croce, Francesco and Flammarion, Nicolas and Hein, Matthias},
  conference={ECCV},
  year={2020}
}
```

**Comment by machanic** [comment]
Where is the poster of your paper? can you upload the poster to github?

**Comment by max-andr** [comment]
There is no poster currently, and we have to see if we are going to make one. ECCV will take place at the end of August and will be fully online so it's not clear whether making a poster makes sense.
