### ISSUE TITLE
FileNotFoundError: '/scratch/maksym/imagenet/val_orig'

### ISSUE THREAD

**Issue by Darylnn** [max-andr/square-attack#7]
![image](https://user-images.githubusercontent.com/61144786/93416382-4dcb1280-f8d8-11ea-8154-3b5898b5eea5.png)

I tried running the basic attack from the example but I ran into this error.
I followed the requirements of installing Pytorch==1.0.0, tensorflow==1.12.0
I was using an Anaconda base with Python 3.6.

Was any of my dependencies different from what is required for the code to run? Thank you for your help

**Comment by max-andr** [comment]
Hi,

You just need to change that path to the path **on your server** that contains the ImageNet validation set.

Best,
Maksym
